export default {
    "GET_CONTRACT_DETAILS": "GET_CONTRACT_DETAILS",
    "CONTRACT_LOADED": "CONTRACT_LOADED",
    "GET_ACTIVE_CONTRACTS": "GET_ACTIVE_CONTRACTS",
    "ACTIVE_CONTRACTS_LOADED": "ACTIVE_CONTRACTS_LOADED"   
};