export default {
    "GET_INBOX_ITEMS": "GET_INBOX_ITEMS",
    "INBOX_ITEMS_LOADED": "INBOX_ITEMS_LOADED",
    "MARK_AS_READ": "MARK_ITEM_AS_READ",
    "MARKED_AS_READ": "MARKED_AS_READ",
    "MARK_ALL_AS_READ": "MARK_ALL_AS_READ",
    
};