export default {
    "GET_PROPOSAL_DETAILS": "GET_PROPOSAL_DETAILS",
    "PROPOSAL_LOADED": "PROPOSAL_LOADED",
    "GET_ACTIVE_PROPOSALS": "GET_ACTIVE_PROPOSALS",
    "ACTIVE_PROPOSALS_LOADED": "ACTIVE_PROPOSALS_LOADED",

    "GET_RFP_DETAILS": "GET_RFP_DETAILS",
    "RFP_LOADED": "RFP_LOADED",

    
};