export default {
    "GET_PO_DETAILS": "GET_PO_DETAILS",
    "PO_LOADED": "PO_LOADED",
    "GET_ACTIVE_POs": "GET_ACTIVE_POs",
    "ACTIVE_POS_LOADED": "ACTIVE_POS_LOADED",
    
    "ESTIMATE_PRICING":"ESTIMATE_PRICING",
    "ESTIMATE_PRICING_CALCULATED": "ESTIMATE_PRICING_CALCULATED",

    "CREATE_PO":"CREATE_PO",
    "PO_CREATED":"PO_CREATED",
    "UPDATE_PO":"UPDATE_PO",
    "PO_UPDATED":"PO_UPDATED",

    "CREATE_INVOICE":"CREATE_INVOICE",
    "INVOICE_CREATED":"INVOICE_CREATED",
};