export default {
    "USER_REGISTERED_CHECKING":"USER_REGISTERED_CHECKING",
    "USER_REGISTERED":"USER_REGISTERED",
    "REGISTER_USER":"REGISTER_USER",
    "REGISTERING_USER":"REGISTERING_USER",
    "GET_BALANCE":"GET_BALANCE",
    "BALANCE_RETRIEVED":"BALANCE_RETRIEVED",
    
};