export default {
    "GET_RFP_DETAILS": "GET_RFP_DETAILS",
    "RFP_LOADED": "RFP_LOADED",
    "GET_ACTIVE_RFPS": "GET_ACTIVE_RFPS",
    "ACTIVE_RFPS_LOADED": "ACTIVE_RFPS_LOADED",

    "CREATE_RFP": "CREATE_RFP",
    "RFP_CREATED": "RFP_CREATED",
    "UPDATE_RFP": "UPDATE_RFP",
    "RFP_UPDATED": "RFP_UPDATED",

    "GET_MY_RFPS": "GET_MY_RFPS",
    "MY_RFPS_LOADED": "MY_RFPS_LOADED",

    "CREATE_PROPOSAL": "CREATE_PROPOSAL",
    "UPDATE_PROPOSAL": "UPDATE_PROPOSAL",
    "PROPOSAL_CREATED": "PROPOSAL_CREATED",
    "PROPOSAL_UPDATED": "PROPOSAL_UPDATED",

    "CREATE_CONTRACT": "CREATE_CONTRACT",
    "CONTRACT_CREATED": "CONTRACT_CREATED"
};
