export default {
    "GET_INVOICE_DETAILS": "GET_INVOICE_DETAILS",
    "INVOICE_LOADED": "INVOICE_LOADED",
    "GET_ACTIVE_INVOICES": "GET_ACTIVE_INVOICES",
    "ACTIVE_INVOICES_LOADED": "ACTIVE_INVOICES_LOADED",
    "GET_BALANCE":"GET_BALANCE",
    "BALANCE_RETRIEVED":"BALANCE_RETRIEVED",
    "PAY_INVOICE":"PAY_INVOICE",
    "INVOICE_PAID":"INVOICE_PAID"
};